export type TransactionType = 'income' | 'expense';
export type TransactionNature = 'fixed' | 'variable';
export type PaymentMethod = 'dinheiro' | 'debito' | 'credito' | 'pix' | 'boleto' | 'transferencia';
export type Recurrence = 'none' | 'monthly' | 'weekly' | 'biweekly' | 'yearly';
export type TransactionStatus = 'paid' | 'pending';
export type HouseholdRole = 'owner' | 'editor' | 'viewer';

export interface Category {
  id: string;
  name: string;
  type: TransactionType;
  icon?: string;
  color?: string;
  isFavorite?: boolean;
}

export interface Transaction {
  id: string;
  type: TransactionType;
  nature: TransactionNature;
  amount: number;
  date: string; // ISO string YYYY-MM-DD
  categoryId: string;
  subcategoryId?: string;
  paymentMethod: PaymentMethod;
  account: string;
  description?: string;
  tags: string[];
  recurrence: Recurrence;
  dueDate?: string; // For fixed expenses
  autoGenerate?: boolean;
  recurrenceSourceId?: string;
  autoGenerated?: boolean;
  installmentCount?: number;
  installmentNumber?: number;
  installmentGroupId?: string;
  creditCardId?: string;
  creditCardCycleKey?: string;
  isCreditCardInterest?: boolean;
  ownerMemberId?: string;
  status: TransactionStatus;
  createdAt: string;
}

export interface CreditCard {
  id: string;
  name: string;
  account: string;
  closingDay: number;
  dueDay: number;
  limit: number;
  interestRateMonthly: number;
  createdAt: string;
}

export interface CreditCardInvoicePayment {
  id: string;
  cardId: string;
  cycleKey: string;
  amount: number;
  paidAt: string;
  createdAt: string;
}

export interface ReminderSettings {
  enabled: boolean;
  daysBefore: number;
  includeOverdue: boolean;
}

export interface CategoryGoal {
  categoryId: string;
  monthlyLimit: number;
  alertThreshold: number;
}

export interface HouseholdMember {
  id: string;
  name: string;
  role: HouseholdRole;
  color?: string;
}

export interface HouseholdSettings {
  enabled: boolean;
  activeMemberId: string;
  members: HouseholdMember[];
}

export interface AppState {
  transactions: Transaction[];
  categories: Category[];
  accounts: string[];
  creditCards: CreditCard[];
  invoicePayments: CreditCardInvoicePayment[];
  reminderSettings: ReminderSettings;
  categoryGoals: CategoryGoal[];
  household: HouseholdSettings;
  skippedOccurrences: Record<string, string[]>;
  defaultPaymentMethod?: PaymentMethod;
  defaultAccount?: string;
}
